### PR TITLE
Upgrading to 64bit

### PR DESCRIPTION
**Pull request by caspahouzer**
Deploying new dist
Build against 3.4.1.GA

### CODE REVIEW

**Comment by fscz** [comment]
thanks

**Comment by caspahouzer** [comment]
My pleasure.

Would it be possible from your side to implement custom names for the generated pdfs?

**Comment by fscz** [comment]
Ok

**Comment by caspahouzer** [comment]
I will create a new issue, yes?

**Comment by fscz** [comment]
yes

**Pull request merged**
